### ISSUE TITLE
Windows does not allow for a colon in the file name, and this will cause the sync to hault

### ISSUE THREAD

**Issue by bryancasler** [putdotio/putio-sync-desktop#42]
Windows will not allow for a colon in a path or file name, among others. If that happens the sync errors out and grinds to a stop. Was unsure if this belonged in the putio-sync or putio-sync-desktop repo so I've posted it in both.

Two changes could be made to address this:

1) Remove colons.

2) When this error is encountered, log it, and continue to the next file

This is the full list of restricted characters that can not be in a path or file URL on Windows. In practice, all of them should be removed.

- `<` (less than)
- `>` (greater than)
- `:` (colon)
- `"` (double quote)
- `/` (forward slash)
- `\` (backslash)
- `|` (vertical bar or pipe)
- `?` (question mark)
- `*` (asterisk)

Source: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions
-

**Comment by cenkalti** [comment]
This is fixed in putio-sync repo. I've updated this repo as well. Your client should auto update. Can you confirm that the files with restricted characters are skipped but do not cause the sync operation to fail please?
